### PR TITLE
use cmake+appveryor+travis to build and run tests on Windows and Linux

### PR DESCRIPTION
**Pull request by menuet**
Hi
Here is my pull request I spoke about in #4 .
There is at least one thing to change: currently, the CI badges use my account and my forked github repo.

### CODE REVIEW

**Comment by PeterSommerlad** [comment]
Please be patient. I am at NDC Techtown the next days and at CPPCon in two weeks and might be too busy to work on that.

**Comment by menuet** [comment]
yes no pb. It is not urgent :-)

**Comment by gotnone** [comment]
@menuet I noticed that in the proposed CMakeLists.txt file that there is no interface library for `scope`  itself.  This is something that cmake users may appreciate.  Ideally, the `scope_test` target could be included only if we are calling cmake on scope17 as the master project, otherwise only enable the interface library.  I am not a cmake expert, but I think something like the following is a start.  As for conditionally enabling targets if the library is the master project, I see that [fmt](https://github.com/fmtlib/fmt/blob/master/CMakeLists.txt) does this.

````
add_library(scope INTERFACE)
target_add_sources(scope INTERFACE ${CMAKE_CURRENT_SOURCE_DIR}/scope.hpp)
target_include_directories(scope INTERFACE
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>
)
target_include_directories(scope SYSTEM INTERFACE
  $<INSTALL_INTERFACE:$<INSTALL_PREFIX>/include/scope17>
)
````

**Comment by gotnone** [comment]
I have a [branch](https://github.com/gotnone/scope17/tree/interface) and [pull request](https://github.com/menuet/scope17/pull/2) with @menuet to address my previous concerns / desires for this pull request.  Thanks for your consideration.

**Comment by gotnone** [comment]
Peter, I never heard back from @menuet about the fixes that I proposed.  I have created a new pull request #13 which bases them off of your new commit, e10de17.  Hopefully, you will consider the changes as they make scope17 a better CMake sub-project.  Thanks.

**Comment by menuet** [comment]
Hi Everybody
Sorry, I had completely forgotten about this pull request that I did a long time ago.
Of course, I agree that it is better to provide an INTERFACE target for developers consuming the cmake config.
(My primary goal was to set up a continuous integration)

**Pull request merged**
